FROM maven:3.9.6-eclipse-temurin-22 AS build
WORKDIR /build
COPY .mvn .mvn
COPY mvnw pom.xml ./
RUN ls -l && cat mvnw
COPY src src
RUN chmod +x mvnw
RUN mvn -B package -DskipTests

FROM eclipse-temurin:22-jdk-alpine
RUN apk add --no-cache ffmpeg
WORKDIR /deployments
COPY --from=build /build/target/quarkus-app/ ./

ENV QUARKUS_LANGCHAIN4J_AZURE_OPENAI_API_KEY="" \
    QUARKUS_LANGCHAIN4J_AZURE_OPENAI_DEPLOYMENT_NAME="" \
    QUARKUS_LANGCHAIN4J_AZURE_OPENAI_API_VERSION="" \
    QUARKUS_LANGCHAIN4J_AZURE_OPENAI_RESOURCE_NAME="" \
    QUARKUS_LANGCHAIN4J_AZURE_OPENAI_CHAT_MODEL_MAX_TOKENS="" \
    QUARKUS_MONGODB_CONNECTION_STRING="" \
    QUARKUS_MONGODB_DATABASE="" \
    QUARKUS_LANGCHAIN4J_CHAT_MEMORY_MEMORY_WINDOW_MAX_MESSAGES="" \
    QUARKUS_LANGCHAIN4J_LOG_REQUESTS="true" \
    QUARKUS_LANGCHAIN4J_LOG_RESPONSES="true" \
    QUARKUS_HTTP_CORS="true" \
    QUARKUS_HTTP_CORS_ORIGIN="*"

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/deployments/quarkus-run.jar"]